### ISSUE TITLE
why use SIN and not underlying public key?

### ISSUE THREAD

**Issue by mvayngrib** [bitpay/bitauth#30]
is it just because the SIN carries an additional few pieces of metadata, such as the SIN type? Or is it for security? As far as I understand the public key is sent with every request, so it's not being kept secret.

one more question: the bitcoin community is very much against reusing private keys, but it seems like SINs are meant to be reused. How do you reconcile the two?

**Comment by braydonf** [comment]
The underlying public key is used, correct. So technically an implementation could not use the SIN, and only the public key.
