### ISSUE TITLE
𝒰nicode 𝔖upport? 

### ISSUE THREAD

**Issue by xcthulhu** [bitpay/bitauth#43]
So I have a port of BitAuth to Clojure, and I am trying to work out differences in the implementations.

One basic problem is that JavaScript can't really handle unicode with codepoints above 65535 (see http://stackoverflow.com/q/19354455 for a discussion of this issue).

The solution I have been using elsewhere is to turn strings lists of bytes (or byte-arrays or whatever) using UTF-16 encoding.  This works in ClojureScript because the hashing function `goog.crypt.sha256` takes lists of bytes, and we always have the Closure libraries around.  So the right thing to do might be to swap out hash.js for [obvious-closure-library](https://www.npmjs.com/package/obvious-closure-library).

**Comment by braydonf** [comment]
This can be fixed by sending a Buffer as the data argument. 

For for example, this change on [line 100 of lib/bitauth.js](https://github.com/bitpay/bitauth/blob/master/lib/bitauth.js#L100) will fix the issue, however would assume "utf-8":
```js
 var hash = (new hashjs.sha256()).update(new Buffer(data, 'utf-8')).digest('hex');
```

**Comment by braydonf** [comment]
Alternatively, specifying as the encoding `utf16le` or `ucs2`: https://nodejs.org/api/buffer.html
