### ISSUE TITLE
Make A Tagged Release For 0.3.1

### ISSUE THREAD

**Issue by xcthulhu** [bitpay/bitauth#50]
Please make a tagged release for 0.3.1

Also, it would help me out over in my [CLJSJS package for bitauth](https://github.com/cljsjs/packages/tree/master/bitauth) if you guys could attach `bitauth.bundle.js` and `bitauth.browser.min.js` to the tagged release, since I am clumsily building these payloads right now for the [cljsjs/bitauth JAR on clojars](https://clojars.org/cljsjs/bitauth), and the CLJSJS maintainers have expressed they would prefer not to do things this way.

Thanks again guys for all of your hard work!

**Comment by braydonf** [comment]
It's been tagged and includes build files: https://github.com/bitpay/bitauth/commit/2618325c7068e430f7c1608d3bc04f2baf68b08c

**Comment by braydonf** [comment]
https://github.com/bitpay/bitauth/releases/tag/v0.3.1
