### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by metachris** [bitpay/bitauth#78]
The latest release is 0.3.2, which uses an old version of https://github.com/cryptocoinjs/secp256k1-node

https://github.com/bitpay/bitauth/blob/90ac1f5f3d088e71383880083642111bcae0b8f7/package.json

I can't manage to build that old version with Node.js v12, only with 10. 

Could you update the dependency and release a new build?

**Comment by calenz** [comment]
Hi BitPay developers, I would like to have a version that works with Node.js v12 as will.

**Comment by cmgustavo** [comment]
Hi! Please use `master` version instead 0.3.2 from npm.

Thanks!

**Comment by calenz** [comment]
@cmgustavo thanks for your reply. However, does that mean I have clone from master and do a npm install locally?

Is there a way to npm install directly on the `master` version? We are running CI pipelines and we really prefer external packages such as yours to be properly tagged for `npm install` to work properly, thanks.

**Comment by nitsujlangston** [comment]
https://www.npmjs.com/package/bitauth/v/0.4.1 released, with Node 12 support
